module.exports = [{
  "chapter_number": 1,
  "bismillah_pre": false,
  "revelation_order": 5,
  "revelation_place": "makkah",
  "name_arabic": "الفاتحة",
  "name_complex": "Al-Fātiĥah",
  "name_simple": "Al-Fatihah",
  "verses_count": 7,
  "verse_from": 1,
  "verse_end": 7,
  "pages": [1, 1],
  "meaning": {"text": "The Opening", "en": "The Opening", "id": "Pembukaan"},
  "hasanah": 1430
}, {
  "chapter_number": 2,
  "bismillah_pre": true,
  "revelation_order": 87,
  "revelation_place": "madinah",
  "name_arabic": "البقرة",
  "name_complex": "Al-Baqarah",
  "name_simple": "Al-Baqarah",
  "verses_count": 286,
  "verse_from": 8,
  "verse_end": 293,
  "pages": [2, 49],
  "meaning": {"text": "The Cow", "en": "The Cow", "id": "Sapi Betina"},
  "hasanah": 262540
}, {
  "chapter_number": 3,
  "bismillah_pre": true,
  "revelation_order": 89,
  "revelation_place": "madinah",
  "name_arabic": "آل عمران",
  "name_complex": "Āli `Imrān",
  "name_simple": "Ali 'Imran",
  "verses_count": 200,
  "verse_from": 294,
  "verse_end": 493,
  "pages": [50, 76],
  "meaning": {"text": "The Family of ’Imrân", "en": "The Family of ’Imrân", "id": "Keluarga Imran"},
  "hasanah": 149850
}, {
  "chapter_number": 4,
  "bismillah_pre": true,
  "revelation_order": 92,
  "revelation_place": "madinah",
  "name_arabic": "النساء",
  "name_complex": "An-Nisā",
  "name_simple": "An-Nisa",
  "verses_count": 176,
  "verse_from": 494,
  "verse_end": 669,
  "pages": [77, 106],
  "meaning": {"text": "Women", "en": "Women", "id": "Wanita"},
  "hasanah": 163320
}, {
  "chapter_number": 5,
  "bismillah_pre": true,
  "revelation_order": 112,
  "revelation_place": "madinah",
  "name_arabic": "المائدة",
  "name_complex": "Al-Mā'idah",
  "name_simple": "Al-Ma'idah",
  "verses_count": 120,
  "verse_from": 670,
  "verse_end": 789,
  "pages": [106, 127],
  "meaning": {"text": "The Spread Table", "en": "The Spread Table", "id": "Jamuan (Hidangan Makanan)"},
  "hasanah": 122060
}, {
  "chapter_number": 6,
  "bismillah_pre": true,
  "revelation_order": 55,
  "revelation_place": "makkah",
  "name_arabic": "الأنعام",
  "name_complex": "Al-'An`ām",
  "name_simple": "Al-An'am",
  "verses_count": 165,
  "verse_from": 790,
  "verse_end": 954,
  "pages": [128, 150],
  "meaning": {"text": "The Cattle", "en": "The Cattle", "id": "Binatang Ternak"},
  "hasanah": 127260
}, {
  "chapter_number": 7,
  "bismillah_pre": true,
  "revelation_order": 39,
  "revelation_place": "makkah",
  "name_arabic": "الأعراف",
  "name_complex": "Al-'A`rāf",
  "name_simple": "Al-A'raf",
  "verses_count": 206,
  "verse_from": 955,
  "verse_end": 1160,
  "pages": [151, 176],
  "meaning": {"text": "The Heights", "en": "The Heights", "id": "Tempat-tempat Tinggi"},
  "hasanah": 144350
}, {
  "chapter_number": 8,
  "bismillah_pre": true,
  "revelation_order": 88,
  "revelation_place": "madinah",
  "name_arabic": "الأنفال",
  "name_complex": "Al-'Anfāl",
  "name_simple": "Al-Anfal",
  "verses_count": 75,
  "verse_from": 1161,
  "verse_end": 1235,
  "pages": [177, 186],
  "meaning": {"text": "The Spoils of War", "en": "The Spoils of War", "id": "Rampasan Perang"},
  "hasanah": 53920
}, {
  "chapter_number": 9,
  "bismillah_pre": false,
  "revelation_order": 113,
  "revelation_place": "madinah",
  "name_arabic": "التوبة",
  "name_complex": "At-Tawbah",
  "name_simple": "At-Tawbah",
  "verses_count": 129,
  "verse_from": 1236,
  "verse_end": 1364,
  "pages": [187, 207],
  "meaning": {"text": "The Repentance", "en": "The Repentance", "id": "Pengampunan"},
  "hasanah": 111150
}, {
  "chapter_number": 10,
  "bismillah_pre": true,
  "revelation_order": 51,
  "revelation_place": "makkah",
  "name_arabic": "يونس",
  "name_complex": "Yūnus",
  "name_simple": "Yunus",
  "verses_count": 109,
  "verse_from": 1365,
  "verse_end": 1473,
  "pages": [208, 221],
  "meaning": {"text": "Jonah", "en": "Jonah", "id": "Yunus"},
  "hasanah": 75890
}, {
  "chapter_number": 11,
  "bismillah_pre": true,
  "revelation_order": 52,
  "revelation_place": "makkah",
  "name_arabic": "هود",
  "name_complex": "Hūd",
  "name_simple": "Hud",
  "verses_count": 123,
  "verse_from": 1474,
  "verse_end": 1596,
  "pages": [221, 235],
  "meaning": {"text": "Hud", "en": "Hud", "id": "Hud"},
  "hasanah": 78170
}, {
  "chapter_number": 12,
  "bismillah_pre": true,
  "revelation_order": 53,
  "revelation_place": "makkah",
  "name_arabic": "يوسف",
  "name_complex": "Yūsuf",
  "name_simple": "Yusuf",
  "verses_count": 111,
  "verse_from": 1597,
  "verse_end": 1707,
  "pages": [235, 248],
  "meaning": {"text": "Joseph", "en": "Joseph", "id": "Yusuf"},
  "hasanah": 73070
}, {
  "chapter_number": 13,
  "bismillah_pre": true,
  "revelation_order": 96,
  "revelation_place": "madinah",
  "name_arabic": "الرعد",
  "name_complex": "Ar-Ra`d",
  "name_simple": "Ar-Ra'd",
  "verses_count": 43,
  "verse_from": 1708,
  "verse_end": 1750,
  "pages": [249, 255],
  "meaning": {"text": "The Thunder", "en": "The Thunder", "id": "Guruh (Petir)"},
  "hasanah": 35450
}, {
  "chapter_number": 14,
  "bismillah_pre": true,
  "revelation_order": 72,
  "revelation_place": "makkah",
  "name_arabic": "ابراهيم",
  "name_complex": "Ibrāhīm",
  "name_simple": "Ibrahim",
  "verses_count": 52,
  "verse_from": 1751,
  "verse_end": 1802,
  "pages": [255, 261],
  "meaning": {"text": "Abrahim", "en": "Abrahim", "id": "Ibrahim"},
  "hasanah": 35390
}, {
  "chapter_number": 15,
  "bismillah_pre": true,
  "revelation_order": 54,
  "revelation_place": "makkah",
  "name_arabic": "الحجر",
  "name_complex": "Al-Ĥijr",
  "name_simple": "Al-Hijr",
  "verses_count": 99,
  "verse_from": 1803,
  "verse_end": 1901,
  "pages": [262, 267],
  "meaning": {"text": "The Rocky Tract", "en": "The Rocky Tract", "id": "Bukit"},
  "hasanah": 28820
}, {
  "chapter_number": 16,
  "bismillah_pre": true,
  "revelation_order": 70,
  "revelation_place": "makkah",
  "name_arabic": "النحل",
  "name_complex": "An-Naĥl",
  "name_simple": "An-Nahl",
  "verses_count": 128,
  "verse_from": 1902,
  "verse_end": 2029,
  "pages": [267, 281],
  "meaning": {"text": "The Bee", "en": "The Bee", "id": "Lebah Madu"},
  "hasanah": 78320
}, {
  "chapter_number": 17,
  "bismillah_pre": true,
  "revelation_order": 50,
  "revelation_place": "makkah",
  "name_arabic": "الإسراء",
  "name_complex": "Al-'Isrā",
  "name_simple": "Al-Isra",
  "verses_count": 111,
  "verse_from": 2030,
  "verse_end": 2140,
  "pages": [282, 293],
  "meaning": {"text": "The Night Journey", "en": "The Night Journey", "id": "Perjalanan Malam"},
  "hasanah": 66430
}, {
  "chapter_number": 18,
  "bismillah_pre": true,
  "revelation_order": 69,
  "revelation_place": "makkah",
  "name_arabic": "الكهف",
  "name_complex": "Al-Kahf",
  "name_simple": "Al-Kahf",
  "verses_count": 110,
  "verse_from": 2141,
  "verse_end": 2250,
  "pages": [293, 304],
  "meaning": {"text": "The Cave", "en": "The Cave", "id": "Para Penghuni Gua"},
  "hasanah": 65520
}, {
  "chapter_number": 19,
  "bismillah_pre": true,
  "revelation_order": 44,
  "revelation_place": "makkah",
  "name_arabic": "مريم",
  "name_complex": "Maryam",
  "name_simple": "Maryam",
  "verses_count": 98,
  "verse_from": 2251,
  "verse_end": 2348,
  "pages": [305, 312],
  "meaning": {"text": "Mary", "en": "Mary", "id": "Maryam"},
  "hasanah": 39350
}, {
  "chapter_number": 20,
  "bismillah_pre": true,
  "revelation_order": 45,
  "revelation_place": "makkah",
  "name_arabic": "طه",
  "name_complex": "Ţāhā",
  "name_simple": "Taha",
  "verses_count": 135,
  "verse_from": 2349,
  "verse_end": 2483,
  "pages": [312, 321],
  "meaning": {"text": "Ta-Ha", "en": "Ta-Ha", "id": "Tha-Ha"},
  "hasanah": 53990
}, {
  "chapter_number": 21,
  "bismillah_pre": true,
  "revelation_order": 73,
  "revelation_place": "makkah",
  "name_arabic": "الأنبياء",
  "name_complex": "Al-'Anbyā",
  "name_simple": "Al-Anbya",
  "verses_count": 112,
  "verse_from": 2484,
  "verse_end": 2595,
  "pages": [322, 331],
  "meaning": {"text": "The Prophets", "en": "The Prophets", "id": "Para Nabi"},
  "hasanah": 50940
}, {
  "chapter_number": 22,
  "bismillah_pre": true,
  "revelation_order": 103,
  "revelation_place": "madinah",
  "name_arabic": "الحج",
  "name_complex": "Al-Ĥaj",
  "name_simple": "Al-Haj",
  "verses_count": 78,
  "verse_from": 2596,
  "verse_end": 2673,
  "pages": [332, 341],
  "meaning": {"text": "The Pilgrimage", "en": "The Pilgrimage", "id": "Haji"},
  "hasanah": 53140
}, {
  "chapter_number": 23,
  "bismillah_pre": true,
  "revelation_order": 74,
  "revelation_place": "makkah",
  "name_arabic": "المؤمنون",
  "name_complex": "Al-Mu'minūn",
  "name_simple": "Al-Mu'minun",
  "verses_count": 118,
  "verse_from": 2674,
  "verse_end": 2791,
  "pages": [342, 349],
  "meaning": {"text": "The Believers", "en": "The Believers", "id": "Orang-orang Mukmin"},
  "hasanah": 44830
}, {
  "chapter_number": 24,
  "bismillah_pre": true,
  "revelation_order": 102,
  "revelation_place": "madinah",
  "name_arabic": "النور",
  "name_complex": "An-Nūr",
  "name_simple": "An-Nur",
  "verses_count": 64,
  "verse_from": 2792,
  "verse_end": 2855,
  "pages": [350, 359],
  "meaning": {"text": "The Light", "en": "The Light", "id": "Cahaya"},
  "hasanah": 57540
}, {
  "chapter_number": 25,
  "bismillah_pre": true,
  "revelation_order": 42,
  "revelation_place": "makkah",
  "name_arabic": "الفرقان",
  "name_complex": "Al-Furqān",
  "name_simple": "Al-Furqan",
  "verses_count": 77,
  "verse_from": 2856,
  "verse_end": 2932,
  "pages": [359, 366],
  "meaning": {"text": "The Criterian", "en": "The Criterian", "id": "Pembeda"},
  "hasanah": 38780
}, {
  "chapter_number": 26,
  "bismillah_pre": true,
  "revelation_order": 47,
  "revelation_place": "makkah",
  "name_arabic": "الشعراء",
  "name_complex": "Ash-Shu`arā",
  "name_simple": "Ash-Shu'ara",
  "verses_count": 227,
  "verse_from": 2933,
  "verse_end": 3159,
  "pages": [367, 376],
  "meaning": {"text": "The Poets", "en": "The Poets", "id": "Penyair"},
  "hasanah": 56300
}, {
  "chapter_number": 27,
  "bismillah_pre": true,
  "revelation_order": 48,
  "revelation_place": "makkah",
  "name_arabic": "النمل",
  "name_complex": "An-Naml",
  "name_simple": "An-Naml",
  "verses_count": 93,
  "verse_from": 3160,
  "verse_end": 3252,
  "pages": [377, 385],
  "meaning": {"text": "The Ant", "en": "The Ant", "id": "Semut"},
  "hasanah": 47900
}, {
  "chapter_number": 28,
  "bismillah_pre": true,
  "revelation_order": 49,
  "revelation_place": "makkah",
  "name_arabic": "القصص",
  "name_complex": "Al-Qaşaş",
  "name_simple": "Al-Qasas",
  "verses_count": 88,
  "verse_from": 3253,
  "verse_end": 3340,
  "pages": [385, 396],
  "meaning": {"text": "The Stories", "en": "The Stories", "id": "Kisah-kisah"},
  "hasanah": 59300
}, {
  "chapter_number": 29,
  "bismillah_pre": true,
  "revelation_order": 85,
  "revelation_place": "makkah",
  "name_arabic": "العنكبوت",
  "name_complex": "Al-`Ankabūt",
  "name_simple": "Al-'Ankabut",
  "verses_count": 69,
  "verse_from": 3341,
  "verse_end": 3409,
  "pages": [396, 404],
  "meaning": {"text": "The Spider", "en": "The Spider", "id": "Laba-laba"},
  "hasanah": 43170
}, {
  "chapter_number": 30,
  "bismillah_pre": true,
  "revelation_order": 84,
  "revelation_place": "makkah",
  "name_arabic": "الروم",
  "name_complex": "Ar-Rūm",
  "name_simple": "Ar-Rum",
  "verses_count": 60,
  "verse_from": 3410,
  "verse_end": 3469,
  "pages": [404, 410],
  "meaning": {"text": "The Romans", "en": "The Romans", "id": "Bangsa Romawi"},
  "hasanah": 34720
}, {
  "chapter_number": 31,
  "bismillah_pre": true,
  "revelation_order": 57,
  "revelation_place": "makkah",
  "name_arabic": "لقمان",
  "name_complex": "Luqmān",
  "name_simple": "Luqman",
  "verses_count": 34,
  "verse_from": 3470,
  "verse_end": 3503,
  "pages": [411, 414],
  "meaning": {"text": "Luqman", "en": "Luqman", "id": "Luqman"},
  "hasanah": 21710
}, {
  "chapter_number": 32,
  "bismillah_pre": true,
  "revelation_order": 75,
  "revelation_place": "makkah",
  "name_arabic": "السجدة",
  "name_complex": "As-Sajdah",
  "name_simple": "As-Sajdah",
  "verses_count": 30,
  "verse_from": 3504,
  "verse_end": 3533,
  "pages": [415, 417],
  "meaning": {"text": "The Prostration", "en": "The Prostration", "id": "Sujud"},
  "hasanah": 15630
}, {
  "chapter_number": 33,
  "bismillah_pre": true,
  "revelation_order": 90,
  "revelation_place": "madinah",
  "name_arabic": "الأحزاب",
  "name_complex": "Al-'Aĥzāb",
  "name_simple": "Al-Ahzab",
  "verses_count": 73,
  "verse_from": 3534,
  "verse_end": 3606,
  "pages": [418, 427],
  "meaning": {"text": "The Combined Forces", "en": "The Combined Forces", "id": "Golongan yang Bersekutu"},
  "hasanah": 57880
}, {
  "chapter_number": 34,
  "bismillah_pre": true,
  "revelation_order": 58,
  "revelation_place": "makkah",
  "name_arabic": "سبإ",
  "name_complex": "Saba",
  "name_simple": "Saba",
  "verses_count": 54,
  "verse_from": 3607,
  "verse_end": 3660,
  "pages": [428, 434],
  "meaning": {"text": "Sheba", "en": "Sheba", "id": "Saba\\'"},
  "hasanah": 35940
}, {
  "chapter_number": 35,
  "bismillah_pre": true,
  "revelation_order": 43,
  "revelation_place": "makkah",
  "name_arabic": "فاطر",
  "name_complex": "Fāţir",
  "name_simple": "Fatir",
  "verses_count": 45,
  "verse_from": 3661,
  "verse_end": 3705,
  "pages": [434, 440],
  "meaning": {"text": "Originator", "en": "Originator", "id": "Pencipta"},
  "hasanah": 32380
}, {
  "chapter_number": 36,
  "bismillah_pre": true,
  "revelation_order": 41,
  "revelation_place": "makkah",
  "name_arabic": "يس",
  "name_complex": "Yā-Sīn",
  "name_simple": "Ya-Sin",
  "verses_count": 83,
  "verse_from": 3706,
  "verse_end": 3788,
  "pages": [440, 445],
  "meaning": {"text": "Ya Sin", "en": "Ya Sin", "id": "Yas Sin"},
  "hasanah": 30680
}, {
  "chapter_number": 37,
  "bismillah_pre": true,
  "revelation_order": 56,
  "revelation_place": "makkah",
  "name_arabic": "الصافات",
  "name_complex": "Aş-Şāffāt",
  "name_simple": "As-Saffat",
  "verses_count": 182,
  "verse_from": 3789,
  "verse_end": 3970,
  "pages": [446, 452],
  "meaning": {"text": "Those who set the Ranks", "en": "Those who set the Ranks", "id": "Barisan-barisan"},
  "hasanah": 39030
}, {
  "chapter_number": 38,
  "bismillah_pre": true,
  "revelation_order": 38,
  "revelation_place": "makkah",
  "name_arabic": "ص",
  "name_complex": "Şād",
  "name_simple": "Sad",
  "verses_count": 88,
  "verse_from": 3971,
  "verse_end": 4058,
  "pages": [453, 458],
  "meaning": {"text": "The Letter \"Saad\"", "en": "The Letter \"Saad\"", "id": "Shad"},
  "hasanah": 30650
}, {
  "chapter_number": 39,
  "bismillah_pre": true,
  "revelation_order": 59,
  "revelation_place": "makkah",
  "name_arabic": "الزمر",
  "name_complex": "Az-Zumar",
  "name_simple": "Az-Zumar",
  "verses_count": 75,
  "verse_from": 4059,
  "verse_end": 4133,
  "pages": [458, 467],
  "meaning": {"text": "The Troops", "en": "The Troops", "id": "Para Rombongan"},
  "hasanah": 48690
}, {
  "chapter_number": 40,
  "bismillah_pre": true,
  "revelation_order": 60,
  "revelation_place": "makkah",
  "name_arabic": "غافر",
  "name_complex": "Ghāfir",
  "name_simple": "Ghafir",
  "verses_count": 85,
  "verse_from": 4134,
  "verse_end": 4218,
  "pages": [467, 476],
  "meaning": {"text": "The Forgiver", "en": "The Forgiver", "id": "Sang Maha Pengampun"},
  "hasanah": 51080
}, {
  "chapter_number": 41,
  "bismillah_pre": true,
  "revelation_order": 61,
  "revelation_place": "makkah",
  "name_arabic": "فصلت",
  "name_complex": "Fuşşilat",
  "name_simple": "Fussilat",
  "verses_count": 54,
  "verse_from": 4219,
  "verse_end": 4272,
  "pages": [477, 482],
  "meaning": {"text": "Explained in Detail", "en": "Explained in Detail", "id": "Yang Dijelaskan"},
  "hasanah": 33650
}, {
  "chapter_number": 42,
  "bismillah_pre": true,
  "revelation_order": 62,
  "revelation_place": "makkah",
  "name_arabic": "الشورى",
  "name_complex": "Ash-Shūraá",
  "name_simple": "Ash-Shuraa",
  "verses_count": 53,
  "verse_from": 4273,
  "verse_end": 4325,
  "pages": [483, 489],
  "meaning": {"text": "The Consultation", "en": "The Consultation", "id": "Musyawarah"},
  "hasanah": 35220
}, {
  "chapter_number": 43,
  "bismillah_pre": true,
  "revelation_order": 63,
  "revelation_place": "makkah",
  "name_arabic": "الزخرف",
  "name_complex": "Az-Zukhruf",
  "name_simple": "Az-Zukhruf",
  "verses_count": 89,
  "verse_from": 4326,
  "verse_end": 4414,
  "pages": [489, 495],
  "meaning": {"text": "The Ornaments of Gold", "en": "The Ornaments of Gold", "id": "Perhiasan"},
  "hasanah": 36090
}, {
  "chapter_number": 44,
  "bismillah_pre": true,
  "revelation_order": 64,
  "revelation_place": "makkah",
  "name_arabic": "الدخان",
  "name_complex": "Ad-Dukhān",
  "name_simple": "Ad-Dukhan",
  "verses_count": 59,
  "verse_from": 4415,
  "verse_end": 4473,
  "pages": [496, 498],
  "meaning": {"text": "The Smoke", "en": "The Smoke", "id": "Kabut"},
  "hasanah": 14740
}, {
  "chapter_number": 45,
  "bismillah_pre": true,
  "revelation_order": 65,
  "revelation_place": "makkah",
  "name_arabic": "الجاثية",
  "name_complex": "Al-Jāthiyah",
  "name_simple": "Al-Jathiyah",
  "verses_count": 37,
  "verse_from": 4474,
  "verse_end": 4510,
  "pages": [499, 502],
  "meaning": {"text": "The Crouching", "en": "The Crouching", "id": "Yang Bertekuk Lutut"},
  "hasanah": 20850
}, {
  "chapter_number": 46,
  "bismillah_pre": true,
  "revelation_order": 66,
  "revelation_place": "makkah",
  "name_arabic": "الأحقاف",
  "name_complex": "Al-'Aĥqāf",
  "name_simple": "Al-Ahqaf",
  "verses_count": 35,
  "verse_from": 4511,
  "verse_end": 4545,
  "pages": [502, 506],
  "meaning": {"text": "The Wind-Curved Sandhills", "en": "The Wind-Curved Sandhills", "id": "Bukit-bukir Pasir"},
  "hasanah": 26670
}, {
  "chapter_number": 47,
  "bismillah_pre": true,
  "revelation_order": 95,
  "revelation_place": "madinah",
  "name_arabic": "محمد",
  "name_complex": "Muĥammad",
  "name_simple": "Muhammad",
  "verses_count": 38,
  "verse_from": 4546,
  "verse_end": 4583,
  "pages": [507, 510],
  "meaning": {"text": "Muhammad", "en": "Muhammad", "id": "Muhammad"},
  "hasanah": 24230
}, {
  "chapter_number": 48,
  "bismillah_pre": true,
  "revelation_order": 111,
  "revelation_place": "madinah",
  "name_arabic": "الفتح",
  "name_complex": "Al-Fatĥ",
  "name_simple": "Al-Fath",
  "verses_count": 29,
  "verse_from": 4584,
  "verse_end": 4612,
  "pages": [511, 515],
  "meaning": {"text": "The Victory", "en": "The Victory", "id": "Kemenangan"},
  "hasanah": 25100
}, {
  "chapter_number": 49,
  "bismillah_pre": true,
  "revelation_order": 106,
  "revelation_place": "madinah",
  "name_arabic": "الحجرات",
  "name_complex": "Al-Ĥujurāt",
  "name_simple": "Al-Hujurat",
  "verses_count": 18,
  "verse_from": 4613,
  "verse_end": 4630,
  "pages": [515, 517],
  "meaning": {"text": "The Rooms", "en": "The Rooms", "id": "Kamar-kamar"},
  "hasanah": 15330
}, {
  "chapter_number": 50,
  "bismillah_pre": true,
  "revelation_order": 34,
  "revelation_place": "makkah",
  "name_arabic": "ق",
  "name_complex": "Qāf",
  "name_simple": "Qaf",
  "verses_count": 45,
  "verse_from": 4631,
  "verse_end": 4675,
  "pages": [518, 520],
  "meaning": {"text": "The Letter \"Qaf\"", "en": "The Letter \"Qaf\"", "id": "Qaf"},
  "hasanah": 15070
}, {
  "chapter_number": 51,
  "bismillah_pre": true,
  "revelation_order": 67,
  "revelation_place": "makkah",
  "name_arabic": "الذاريات",
  "name_complex": "Adh-Dhāriyāt",
  "name_simple": "Adh-Dhariyat",
  "verses_count": 60,
  "verse_from": 4676,
  "verse_end": 4735,
  "pages": [520, 523],
  "meaning": {"text": "The Winnowing Winds", "en": "The Winnowing Winds", "id": "Angin yang Menerbangkan"},
  "hasanah": 15460
}, {
  "chapter_number": 52,
  "bismillah_pre": true,
  "revelation_order": 76,
  "revelation_place": "makkah",
  "name_arabic": "الطور",
  "name_complex": "Aţ-Ţūr",
  "name_simple": "At-Tur",
  "verses_count": 49,
  "verse_from": 4736,
  "verse_end": 4784,
  "pages": [523, 525],
  "meaning": {"text": "The Mount", "en": "The Mount", "id": "Bukit"},
  "hasanah": 13240
}, {
  "chapter_number": 53,
  "bismillah_pre": true,
  "revelation_order": 23,
  "revelation_place": "makkah",
  "name_arabic": "النجم",
  "name_complex": "An-Najm",
  "name_simple": "An-Najm",
  "verses_count": 62,
  "verse_from": 4785,
  "verse_end": 4846,
  "pages": [526, 528],
  "meaning": {"text": "The Star", "en": "The Star", "id": "Bintang"},
  "hasanah": 14330
}, {
  "chapter_number": 54,
  "bismillah_pre": true,
  "revelation_order": 37,
  "revelation_place": "makkah",
  "name_arabic": "القمر",
  "name_complex": "Al-Qamar",
  "name_simple": "Al-Qamar",
  "verses_count": 55,
  "verse_from": 4847,
  "verse_end": 4901,
  "pages": [528, 531],
  "meaning": {"text": "The Moon", "en": "The Moon", "id": "Bulan"},
  "hasanah": 14690
}, {
  "chapter_number": 55,
  "bismillah_pre": true,
  "revelation_order": 97,
  "revelation_place": "madinah",
  "name_arabic": "الرحمن",
  "name_complex": "Ar-Raĥmān",
  "name_simple": "Ar-Rahman",
  "verses_count": 78,
  "verse_from": 4902,
  "verse_end": 4979,
  "pages": [531, 534],
  "meaning": {"text": "The Beneficent", "en": "The Beneficent", "id": "Yang Maha Pemurah"},
  "hasanah": 16470
}, {
  "chapter_number": 56,
  "bismillah_pre": true,
  "revelation_order": 46,
  "revelation_place": "makkah",
  "name_arabic": "الواقعة",
  "name_complex": "Al-Wāqi`ah",
  "name_simple": "Al-Waqi'ah",
  "verses_count": 96,
  "verse_from": 4980,
  "verse_end": 5075,
  "pages": [534, 537],
  "meaning": {"text": "The Inevitable", "en": "The Inevitable", "id": "Hari Kiamat"},
  "hasanah": 17560
}, {
  "chapter_number": 57,
  "bismillah_pre": true,
  "revelation_order": 94,
  "revelation_place": "madinah",
  "name_arabic": "الحديد",
  "name_complex": "Al-Ĥadīd",
  "name_simple": "Al-Hadid",
  "verses_count": 29,
  "verse_from": 5076,
  "verse_end": 5104,
  "pages": [537, 541],
  "meaning": {"text": "The Iron", "en": "The Iron", "id": "Besi"},
  "hasanah": 25450
}, {
  "chapter_number": 58,
  "bismillah_pre": true,
  "revelation_order": 105,
  "revelation_place": "madinah",
  "name_arabic": "المجادلة",
  "name_complex": "Al-Mujādila",
  "name_simple": "Al-Mujadila",
  "verses_count": 22,
  "verse_from": 5105,
  "verse_end": 5126,
  "pages": [542, 545],
  "meaning": {"text": "The Pleading Woman", "en": "The Pleading Woman", "id": "Wanita yang Menggugat"},
  "hasanah": 20460
}, {
  "chapter_number": 59,
  "bismillah_pre": true,
  "revelation_order": 101,
  "revelation_place": "madinah",
  "name_arabic": "الحشر",
  "name_complex": "Al-Ĥashr",
  "name_simple": "Al-Hashr",
  "verses_count": 24,
  "verse_from": 5127,
  "verse_end": 5150,
  "pages": [545, 548],
  "meaning": {"text": "The Exile", "en": "The Exile", "id": "Pengusiran"},
  "hasanah": 19700
}, {
  "chapter_number": 60,
  "bismillah_pre": true,
  "revelation_order": 91,
  "revelation_place": "madinah",
  "name_arabic": "الممتحنة",
  "name_complex": "Al-Mumtaĥanah",
  "name_simple": "Al-Mumtahanah",
  "verses_count": 13,
  "verse_from": 5151,
  "verse_end": 5163,
  "pages": [549, 551],
  "meaning": {"text": "She that is to be examined", "en": "She that is to be examined", "id": "Wanita yang Diuji"},
  "hasanah": 15600
}, {
  "chapter_number": 61,
  "bismillah_pre": true,
  "revelation_order": 109,
  "revelation_place": "madinah",
  "name_arabic": "الصف",
  "name_complex": "Aş-Şaf",
  "name_simple": "As-Saf",
  "verses_count": 14,
  "verse_from": 5164,
  "verse_end": 5177,
  "pages": [551, 552],
  "meaning": {"text": "The Ranks", "en": "The Ranks", "id": "Barisan"},
  "hasanah": 9660
}, {
  "chapter_number": 62,
  "bismillah_pre": true,
  "revelation_order": 110,
  "revelation_place": "madinah",
  "name_arabic": "الجمعة",
  "name_complex": "Al-Jumu`ah",
  "name_simple": "Al-Jumu'ah",
  "verses_count": 11,
  "verse_from": 5178,
  "verse_end": 5188,
  "pages": [553, 554],
  "meaning": {"text": "The Congregation, Friday", "en": "The Congregation, Friday", "id": "Hari Jum\\'at"},
  "hasanah": 7680
}, {
  "chapter_number": 63,
  "bismillah_pre": true,
  "revelation_order": 104,
  "revelation_place": "madinah",
  "name_arabic": "المنافقون",
  "name_complex": "Al-Munāfiqūn",
  "name_simple": "Al-Munafiqun",
  "verses_count": 11,
  "verse_from": 5189,
  "verse_end": 5199,
  "pages": [554, 555],
  "meaning": {"text": "The Hypocrites", "en": "The Hypocrites", "id": "Kaum Munafik"},
  "hasanah": 8010
}, {
  "chapter_number": 64,
  "bismillah_pre": true,
  "revelation_order": 108,
  "revelation_place": "madinah",
  "name_arabic": "التغابن",
  "name_complex": "At-Taghābun",
  "name_simple": "At-Taghabun",
  "verses_count": 18,
  "verse_from": 5200,
  "verse_end": 5217,
  "pages": [556, 557],
  "meaning": {"text": "The Mutual Disillusion", "en": "The Mutual Disillusion", "id": "Hari Dinampakkan Kesalahan"},
  "hasanah": 10910
}, {
  "chapter_number": 65,
  "bismillah_pre": true,
  "revelation_order": 99,
  "revelation_place": "madinah",
  "name_arabic": "الطلاق",
  "name_complex": "Aţ-Ţalāq",
  "name_simple": "At-Talaq",
  "verses_count": 12,
  "verse_from": 5218,
  "verse_end": 5229,
  "pages": [558, 559],
  "meaning": {"text": "The Divorce", "en": "The Divorce", "id": "Perceraian"},
  "hasanah": 12030
}, {
  "chapter_number": 66,
  "bismillah_pre": true,
  "revelation_order": 107,
  "revelation_place": "madinah",
  "name_arabic": "التحريم",
  "name_complex": "At-Taĥrīm",
  "name_simple": "At-Tahrim",
  "verses_count": 12,
  "verse_from": 5230,
  "verse_end": 5241,
  "pages": [560, 561],
  "meaning": {"text": "The Prohibtiion", "en": "The Prohibtiion", "id": "Mengharamkan"},
  "hasanah": 11050
}, {
  "chapter_number": 67,
  "bismillah_pre": true,
  "revelation_order": 77,
  "revelation_place": "makkah",
  "name_arabic": "الملك",
  "name_complex": "Al-Mulk",
  "name_simple": "Al-Mulk",
  "verses_count": 30,
  "verse_from": 5242,
  "verse_end": 5271,
  "pages": [562, 564],
  "meaning": {"text": "The Sovereignty", "en": "The Sovereignty", "id": "Kerajaan"},
  "hasanah": 13470
}, {
  "chapter_number": 68,
  "bismillah_pre": true,
  "revelation_order": 2,
  "revelation_place": "makkah",
  "name_arabic": "القلم",
  "name_complex": "Al-Qalam",
  "name_simple": "Al-Qalam",
  "verses_count": 52,
  "verse_from": 5272,
  "verse_end": 5323,
  "pages": [564, 566],
  "meaning": {"text": "The Pen", "en": "The Pen", "id": "Pena"},
  "hasanah": 12890
}, {
  "chapter_number": 69,
  "bismillah_pre": true,
  "revelation_order": 78,
  "revelation_place": "makkah",
  "name_arabic": "الحاقة",
  "name_complex": "Al-Ĥāqqah",
  "name_simple": "Al-Haqqah",
  "verses_count": 52,
  "verse_from": 5324,
  "verse_end": 5375,
  "pages": [566, 568],
  "meaning": {"text": "The Reality", "en": "The Reality", "id": "Kenyataan (Hari Kiamat)"},
  "hasanah": 11330
}, {
  "chapter_number": 70,
  "bismillah_pre": true,
  "revelation_order": 79,
  "revelation_place": "makkah",
  "name_arabic": "المعارج",
  "name_complex": "Al-Ma`ārij",
  "name_simple": "Al-Ma'arij",
  "verses_count": 44,
  "verse_from": 5376,
  "verse_end": 5419,
  "pages": [568, 570],
  "meaning": {"text": "The Ascending Stairways", "en": "The Ascending Stairways", "id": "Tempat yang Naik"},
  "hasanah": 9710
}, {
  "chapter_number": 71,
  "bismillah_pre": true,
  "revelation_order": 71,
  "revelation_place": "makkah",
  "name_arabic": "نوح",
  "name_complex": "Nūĥ",
  "name_simple": "Nuh",
  "verses_count": 28,
  "verse_from": 5420,
  "verse_end": 5447,
  "pages": [570, 571],
  "meaning": {"text": "Noah", "en": "Noah", "id": "Nuh"},
  "hasanah": 9650
}, {
  "chapter_number": 72,
  "bismillah_pre": true,
  "revelation_order": 40,
  "revelation_place": "makkah",
  "name_arabic": "الجن",
  "name_complex": "Al-Jinn",
  "name_simple": "Al-Jinn",
  "verses_count": 28,
  "verse_from": 5448,
  "verse_end": 5475,
  "pages": [572, 573],
  "meaning": {"text": "The Jinn", "en": "The Jinn", "id": "Jin"},
  "hasanah": 11090
}, {
  "chapter_number": 73,
  "bismillah_pre": true,
  "revelation_order": 3,
  "revelation_place": "makkah",
  "name_arabic": "المزمل",
  "name_complex": "Al-Muzzammil",
  "name_simple": "Al-Muzzammil",
  "verses_count": 20,
  "verse_from": 5476,
  "verse_end": 5495,
  "pages": [574, 575],
  "meaning": {"text": "The Enshrouded One", "en": "The Enshrouded One", "id": "Orang yang Berselimut"},
  "hasanah": 8540
}, {
  "chapter_number": 74,
  "bismillah_pre": true,
  "revelation_order": 4,
  "revelation_place": "makkah",
  "name_arabic": "المدثر",
  "name_complex": "Al-Muddaththir",
  "name_simple": "Al-Muddaththir",
  "verses_count": 56,
  "verse_from": 5496,
  "verse_end": 5551,
  "pages": [575, 577],
  "meaning": {"text": "The Cloaked One", "en": "The Cloaked One", "id": "Orang yang Berkemul"},
  "hasanah": 10350
}, {
  "chapter_number": 75,
  "bismillah_pre": true,
  "revelation_order": 31,
  "revelation_place": "makkah",
  "name_arabic": "القيامة",
  "name_complex": "Al-Qiyāmah",
  "name_simple": "Al-Qiyamah",
  "verses_count": 40,
  "verse_from": 5552,
  "verse_end": 5591,
  "pages": [577, 578],
  "meaning": {"text": "The Resurrection", "en": "The Resurrection", "id": "Hari Berbangkit"},
  "hasanah": 6760
}, {
  "chapter_number": 76,
  "bismillah_pre": true,
  "revelation_order": 98,
  "revelation_place": "madinah",
  "name_arabic": "الانسان",
  "name_complex": "Al-'Insān",
  "name_simple": "Al-Insan",
  "verses_count": 31,
  "verse_from": 5592,
  "verse_end": 5622,
  "pages": [578, 580],
  "meaning": {"text": "The Man", "en": "The Man", "id": "Manusia"},
  "hasanah": 10870
}, {
  "chapter_number": 77,
  "bismillah_pre": true,
  "revelation_order": 33,
  "revelation_place": "makkah",
  "name_arabic": "المرسلات",
  "name_complex": "Al-Mursalāt",
  "name_simple": "Al-Mursalat",
  "verses_count": 50,
  "verse_from": 5623,
  "verse_end": 5672,
  "pages": [580, 581],
  "meaning": {"text": "The Emissaries", "en": "The Emissaries", "id": "Malaikat-malaikan yang Diutus"},
  "hasanah": 8410
}, {
  "chapter_number": 78,
  "bismillah_pre": true,
  "revelation_order": 80,
  "revelation_place": "makkah",
  "name_arabic": "النبإ",
  "name_complex": "An-Naba",
  "name_simple": "An-Naba",
  "verses_count": 40,
  "verse_from": 5673,
  "verse_end": 5712,
  "pages": [582, 583],
  "meaning": {"text": "The Tidings", "en": "The Tidings", "id": "Berita Besar"},
  "hasanah": 7960
}, {
  "chapter_number": 79,
  "bismillah_pre": true,
  "revelation_order": 81,
  "revelation_place": "makkah",
  "name_arabic": "النازعات",
  "name_complex": "An-Nāzi`āt",
  "name_simple": "An-Nazi'at",
  "verses_count": 46,
  "verse_from": 5713,
  "verse_end": 5758,
  "pages": [583, 584],
  "meaning": {"text": "Those who drag forth", "en": "Those who drag forth", "id": "Malaikat yang Mencabut"},
  "hasanah": 7850
}, {
  "chapter_number": 80,
  "bismillah_pre": true,
  "revelation_order": 24,
  "revelation_place": "makkah",
  "name_arabic": "عبس",
  "name_complex": "`Abasa",
  "name_simple": "'Abasa",
  "verses_count": 42,
  "verse_from": 5759,
  "verse_end": 5800,
  "pages": [585, 585],
  "meaning": {"text": "He Frowned", "en": "He Frowned", "id": "Ia Bermuka Masam"},
  "hasanah": 5520
}, {
  "chapter_number": 81,
  "bismillah_pre": true,
  "revelation_order": 7,
  "revelation_place": "makkah",
  "name_arabic": "التكوير",
  "name_complex": "At-Takwīr",
  "name_simple": "At-Takwir",
  "verses_count": 29,
  "verse_from": 5801,
  "verse_end": 5829,
  "pages": [586, 586],
  "meaning": {"text": "The Overthrowing", "en": "The Overthrowing", "id": "Menggulung"},
  "hasanah": 4350
}, {
  "chapter_number": 82,
  "bismillah_pre": true,
  "revelation_order": 82,
  "revelation_place": "makkah",
  "name_arabic": "الإنفطار",
  "name_complex": "Al-'Infiţār",
  "name_simple": "Al-Infitar",
  "verses_count": 19,
  "verse_from": 5830,
  "verse_end": 5848,
  "pages": [587, 587],
  "meaning": {"text": "The Cleaving", "en": "The Cleaving", "id": "Terbelah"},
  "hasanah": 3330
}, {
  "chapter_number": 83,
  "bismillah_pre": true,
  "revelation_order": 86,
  "revelation_place": "makkah",
  "name_arabic": "المطففين",
  "name_complex": "Al-Muţaffifīn",
  "name_simple": "Al-Mutaffifin",
  "verses_count": 36,
  "verse_from": 5849,
  "verse_end": 5884,
  "pages": [587, 589],
  "meaning": {"text": "The Defrauding", "en": "The Defrauding", "id": "Orang-orang Curang"},
  "hasanah": 7500
}, {
  "chapter_number": 84,
  "bismillah_pre": true,
  "revelation_order": 83,
  "revelation_place": "makkah",
  "name_arabic": "الإنشقاق",
  "name_complex": "Al-'Inshiqāq",
  "name_simple": "Al-Inshiqaq",
  "verses_count": 25,
  "verse_from": 5885,
  "verse_end": 5909,
  "pages": [589, 589],
  "meaning": {"text": "The Sundering", "en": "The Sundering", "id": "Terbelah"},
  "hasanah": 4450
}, {
  "chapter_number": 85,
  "bismillah_pre": true,
  "revelation_order": 27,
  "revelation_place": "makkah",
  "name_arabic": "البروج",
  "name_complex": "Al-Burūj",
  "name_simple": "Al-Buruj",
  "verses_count": 22,
  "verse_from": 5910,
  "verse_end": 5931,
  "pages": [590, 590],
  "meaning": {"text": "The Mansions of the Stars", "en": "The Mansions of the Stars", "id": "Gugusan Bintang"},
  "hasanah": 4690
}, {
  "chapter_number": 86,
  "bismillah_pre": true,
  "revelation_order": 36,
  "revelation_place": "makkah",
  "name_arabic": "الطارق",
  "name_complex": "Aţ-Ţāriq",
  "name_simple": "At-Tariq",
  "verses_count": 17,
  "verse_from": 5932,
  "verse_end": 5948,
  "pages": [591, 591],
  "meaning": {"text": "The Nightcommer", "en": "The Nightcommer", "id": "Yang Datang di Malam Hari"},
  "hasanah": 2540
}, {
  "chapter_number": 87,
  "bismillah_pre": true,
  "revelation_order": 8,
  "revelation_place": "makkah",
  "name_arabic": "الأعلى",
  "name_complex": "Al-'A`lá",
  "name_simple": "Al-A'la",
  "verses_count": 19,
  "verse_from": 5949,
  "verse_end": 5967,
  "pages": [591, 592],
  "meaning": {"text": "The Most High", "en": "The Most High", "id": "Yang Paling Tinggi"},
  "hasanah": 2960
}, {
  "chapter_number": 88,
  "bismillah_pre": true,
  "revelation_order": 68,
  "revelation_place": "makkah",
  "name_arabic": "الغاشية",
  "name_complex": "Al-Ghāshiyah",
  "name_simple": "Al-Ghashiyah",
  "verses_count": 26,
  "verse_from": 5968,
  "verse_end": 5993,
  "pages": [592, 592],
  "meaning": {"text": "The Overwhelming", "en": "The Overwhelming", "id": "Hari Pembalasan"},
  "hasanah": 3820
}, {
  "chapter_number": 89,
  "bismillah_pre": true,
  "revelation_order": 10,
  "revelation_place": "makkah",
  "name_arabic": "الفجر",
  "name_complex": "Al-Fajr",
  "name_simple": "Al-Fajr",
  "verses_count": 30,
  "verse_from": 5994,
  "verse_end": 6023,
  "pages": [593, 594],
  "meaning": {"text": "The Dawn", "en": "The Dawn", "id": "Fajar"},
  "hasanah": 5840
}, {
  "chapter_number": 90,
  "bismillah_pre": true,
  "revelation_order": 35,
  "revelation_place": "makkah",
  "name_arabic": "البلد",
  "name_complex": "Al-Balad",
  "name_simple": "Al-Balad",
  "verses_count": 20,
  "verse_from": 6024,
  "verse_end": 6043,
  "pages": [594, 594],
  "meaning": {"text": "The City", "en": "The City", "id": "Negeri"},
  "hasanah": 3420
}, {
  "chapter_number": 91,
  "bismillah_pre": true,
  "revelation_order": 26,
  "revelation_place": "makkah",
  "name_arabic": "الشمس",
  "name_complex": "Ash-Shams",
  "name_simple": "Ash-Shams",
  "verses_count": 15,
  "verse_from": 6044,
  "verse_end": 6058,
  "pages": [595, 595],
  "meaning": {"text": "The Sun", "en": "The Sun", "id": "Matahari"},
  "hasanah": 2530
}, {
  "chapter_number": 92,
  "bismillah_pre": true,
  "revelation_order": 9,
  "revelation_place": "makkah",
  "name_arabic": "الليل",
  "name_complex": "Al-Layl",
  "name_simple": "Al-Layl",
  "verses_count": 21,
  "verse_from": 6059,
  "verse_end": 6079,
  "pages": [595, 596],
  "meaning": {"text": "The Night", "en": "The Night", "id": "Malam"},
  "hasanah": 3140
}, {
  "chapter_number": 93,
  "bismillah_pre": true,
  "revelation_order": 11,
  "revelation_place": "makkah",
  "name_arabic": "الضحى",
  "name_complex": "Ađ-Đuĥaá",
  "name_simple": "Ad-Duhaa",
  "verses_count": 11,
  "verse_from": 6080,
  "verse_end": 6090,
  "pages": [596, 596],
  "meaning": {"text": "The Morning Hours", "en": "The Morning Hours", "id": "Waktu Dhuha"},
  "hasanah": 1650
}, {
  "chapter_number": 94,
  "bismillah_pre": true,
  "revelation_order": 12,
  "revelation_place": "makkah",
  "name_arabic": "الشرح",
  "name_complex": "Ash-Sharĥ",
  "name_simple": "Ash-Sharh",
  "verses_count": 8,
  "verse_from": 6091,
  "verse_end": 6098,
  "pages": [596, 596],
  "meaning": {"text": "The Relief", "en": "The Relief", "id": "Melapangkan"},
  "hasanah": 1020
}, {
  "chapter_number": 95,
  "bismillah_pre": true,
  "revelation_order": 28,
  "revelation_place": "makkah",
  "name_arabic": "التين",
  "name_complex": "At-Tīn",
  "name_simple": "At-Tin",
  "verses_count": 8,
  "verse_from": 6099,
  "verse_end": 6106,
  "pages": [597, 597],
  "meaning": {"text": "The Fig", "en": "The Fig", "id": "Buah Tin"},
  "hasanah": 1620
}, {
  "chapter_number": 96,
  "bismillah_pre": true,
  "revelation_order": 1,
  "revelation_place": "makkah",
  "name_arabic": "العلق",
  "name_complex": "Al-`Alaq",
  "name_simple": "Al-'Alaq",
  "verses_count": 19,
  "verse_from": 6107,
  "verse_end": 6125,
  "pages": [597, 597],
  "meaning": {"text": "The Clot", "en": "The Clot", "id": "Segumpal Darah"},
  "hasanah": 2880
}, {
  "chapter_number": 97,
  "bismillah_pre": true,
  "revelation_order": 25,
  "revelation_place": "makkah",
  "name_arabic": "القدر",
  "name_complex": "Al-Qadr",
  "name_simple": "Al-Qadr",
  "verses_count": 5,
  "verse_from": 6126,
  "verse_end": 6130,
  "pages": [598, 598],
  "meaning": {"text": "The Power", "en": "The Power", "id": "Kemuliaan"},
  "hasanah": 1150
}, {
  "chapter_number": 98,
  "bismillah_pre": true,
  "revelation_order": 100,
  "revelation_place": "madinah",
  "name_arabic": "البينة",
  "name_complex": "Al-Bayyinah",
  "name_simple": "Al-Bayyinah",
  "verses_count": 8,
  "verse_from": 6131,
  "verse_end": 6138,
  "pages": [598, 599],
  "meaning": {"text": "The Clear Proof", "en": "The Clear Proof", "id": "Pembuktian"},
  "hasanah": 4040
}, {
  "chapter_number": 99,
  "bismillah_pre": true,
  "revelation_order": 93,
  "revelation_place": "madinah",
  "name_arabic": "الزلزلة",
  "name_complex": "Az-Zalzalah",
  "name_simple": "Az-Zalzalah",
  "verses_count": 8,
  "verse_from": 6139,
  "verse_end": 6146,
  "pages": [599, 599],
  "meaning": {"text": "The Earthquake", "en": "The Earthquake", "id": "Kegoncangan"},
  "hasanah": 1580
}, {
  "chapter_number": 100,
  "bismillah_pre": true,
  "revelation_order": 14,
  "revelation_place": "makkah",
  "name_arabic": "العاديات",
  "name_complex": "Al-`Ādiyāt",
  "name_simple": "Al-'Adiyat",
  "verses_count": 11,
  "verse_from": 6147,
  "verse_end": 6157,
  "pages": [599, 600],
  "meaning": {"text": "The Courser", "en": "The Courser", "id": "Berlari Kencang"},
  "hasanah": 1690
}, {
  "chapter_number": 101,
  "bismillah_pre": true,
  "revelation_order": 30,
  "revelation_place": "makkah",
  "name_arabic": "القارعة",
  "name_complex": "Al-Qāri`ah",
  "name_simple": "Al-Qari'ah",
  "verses_count": 11,
  "verse_from": 6158,
  "verse_end": 6168,
  "pages": [600, 600],
  "meaning": {"text": "The Calamity", "en": "The Calamity", "id": "Hari Kiamat"},
  "hasanah": 1600
}, {
  "chapter_number": 102,
  "bismillah_pre": true,
  "revelation_order": 16,
  "revelation_place": "makkah",
  "name_arabic": "التكاثر",
  "name_complex": "At-Takāthur",
  "name_simple": "At-Takathur",
  "verses_count": 8,
  "verse_from": 6169,
  "verse_end": 6176,
  "pages": [600, 600],
  "meaning": {"text": "The Rivalry in world increase", "en": "The Rivalry in world increase", "id": "Bermegah-megahan"},
  "hasanah": 1230
}, {
  "chapter_number": 103,
  "bismillah_pre": true,
  "revelation_order": 13,
  "revelation_place": "makkah",
  "name_arabic": "العصر",
  "name_complex": "Al-`Aşr",
  "name_simple": "Al-'Asr",
  "verses_count": 3,
  "verse_from": 6177,
  "verse_end": 6179,
  "pages": [601, 601],
  "meaning": {"text": "The Declining Day", "en": "The Declining Day", "id": "Waktu Sore"},
  "hasanah": 730
}, {
  "chapter_number": 104,
  "bismillah_pre": true,
  "revelation_order": 32,
  "revelation_place": "makkah",
  "name_arabic": "الهمزة",
  "name_complex": "Al-Humazah",
  "name_simple": "Al-Humazah",
  "verses_count": 9,
  "verse_from": 6180,
  "verse_end": 6188,
  "pages": [601, 601],
  "meaning": {"text": "The Traducer", "en": "The Traducer", "id": "Pengumpat"},
  "hasanah": 1340
}, {
  "chapter_number": 105,
  "bismillah_pre": true,
  "revelation_order": 19,
  "revelation_place": "makkah",
  "name_arabic": "الفيل",
  "name_complex": "Al-Fīl",
  "name_simple": "Al-Fil",
  "verses_count": 5,
  "verse_from": 6189,
  "verse_end": 6193,
  "pages": [601, 601],
  "meaning": {"text": "The Elephant", "en": "The Elephant", "id": "Gajah"},
  "hasanah": 970
}, {
  "chapter_number": 106,
  "bismillah_pre": true,
  "revelation_order": 29,
  "revelation_place": "makkah",
  "name_arabic": "قريش",
  "name_complex": "Quraysh",
  "name_simple": "Quraysh",
  "verses_count": 4,
  "verse_from": 6194,
  "verse_end": 6197,
  "pages": [602, 602],
  "meaning": {"text": "Quraysh", "en": "Quraysh", "id": "Suku Quraisy"},
  "hasanah": 770
}, {
  "chapter_number": 107,
  "bismillah_pre": true,
  "revelation_order": 17,
  "revelation_place": "makkah",
  "name_arabic": "الماعون",
  "name_complex": "Al-Mā`ūn",
  "name_simple": "Al-Ma'un",
  "verses_count": 7,
  "verse_from": 6198,
  "verse_end": 6204,
  "pages": [602, 602],
  "meaning": {"text": "The Small Kindesses", "en": "The Small Kindesses", "id": "Barang yang Berguna"},
  "hasanah": 1140
}, {
  "chapter_number": 108,
  "bismillah_pre": true,
  "revelation_order": 15,
  "revelation_place": "makkah",
  "name_arabic": "الكوثر",
  "name_complex": "Al-Kawthar",
  "name_simple": "Al-Kawthar",
  "verses_count": 3,
  "verse_from": 6205,
  "verse_end": 6207,
  "pages": [602, 602],
  "meaning": {"text": "The Abundance", "en": "The Abundance", "id": "Nikmat Berlimpah"},
  "hasanah": 430
}, {
  "chapter_number": 109,
  "bismillah_pre": true,
  "revelation_order": 18,
  "revelation_place": "makkah",
  "name_arabic": "الكافرون",
  "name_complex": "Al-Kāfirūn",
  "name_simple": "Al-Kafirun",
  "verses_count": 6,
  "verse_from": 6208,
  "verse_end": 6213,
  "pages": [603, 603],
  "meaning": {"text": "The Disbelievers", "en": "The Disbelievers", "id": "Orang-orang Kafir"},
  "hasanah": 990
}, {
  "chapter_number": 110,
  "bismillah_pre": true,
  "revelation_order": 114,
  "revelation_place": "madinah",
  "name_arabic": "النصر",
  "name_complex": "An-Naşr",
  "name_simple": "An-Nasr",
  "verses_count": 3,
  "verse_from": 6214,
  "verse_end": 6216,
  "pages": [603, 603],
  "meaning": {"text": "The Divine Support", "en": "The Divine Support", "id": "Pertolongan"},
  "hasanah": 800
}, {
  "chapter_number": 111,
  "bismillah_pre": true,
  "revelation_order": 6,
  "revelation_place": "makkah",
  "name_arabic": "المسد",
  "name_complex": "Al-Masad",
  "name_simple": "Al-Masad",
  "verses_count": 5,
  "verse_from": 6217,
  "verse_end": 6221,
  "pages": [603, 603],
  "meaning": {"text": "The Palm Fiber", "en": "The Palm Fiber", "id": "Gejolak Api (Sabut)"},
  "hasanah": 810
}, {
  "chapter_number": 112,
  "bismillah_pre": true,
  "revelation_order": 22,
  "revelation_place": "makkah",
  "name_arabic": "الإخلاص",
  "name_complex": "Al-'Ikhlāş",
  "name_simple": "Al-Ikhlas",
  "verses_count": 4,
  "verse_from": 6222,
  "verse_end": 6225,
  "pages": [604, 604],
  "meaning": {"text": "The Sincerity", "en": "The Sincerity", "id": "Ikhlash"},
  "hasanah": 470
}, {
  "chapter_number": 113,
  "bismillah_pre": true,
  "revelation_order": 20,
  "revelation_place": "makkah",
  "name_arabic": "الفلق",
  "name_complex": "Al-Falaq",
  "name_simple": "Al-Falaq",
  "verses_count": 5,
  "verse_from": 6226,
  "verse_end": 6230,
  "pages": [604, 604],
  "meaning": {"text": "The Daybreak", "en": "The Daybreak", "id": "Waktu Shubuh"},
  "hasanah": 730
}, {
  "chapter_number": 114,
  "bismillah_pre": true,
  "revelation_order": 21,
  "revelation_place": "makkah",
  "name_arabic": "الناس",
  "name_complex": "An-Nās",
  "name_simple": "An-Nas",
  "verses_count": 6,
  "verse_from": 6231,
  "verse_end": 6236,
  "pages": [604, 604],
  "meaning": {"text": "The Mankind", "en": "The Mankind", "id": "Umat Manusia"},
  "hasanah": 800
}]


